name: 'Use kubectl in DOKS'
description: 'Use kubectl inside a DOKS'
inputs:
  kubectl:
    description: 'Kubectl command to execute'
    required: true
  cluster:
    description: 'Name of the cluster in Digital Ocean'
    required: true
  accessToken:
    description: 'Digital Ocean API Access Token'
    required: true
runs:
  using: "composite"
  steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ inputs.accessToken }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ inputs.cluster }}
        shell: bash

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl ${{ inputs.kubectl }}
        shell: bash
